# Generated by Django 5.2.7 on 2025-11-07 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0002_ingresso_thumbnail_ingresso_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
