# Generated by Django 5.2.7 on 2025-12-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0004_ingresso_status_alter_ingresso_estoque_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocompra',
            name='data_horario_evento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
