# Generated by Django 5.2.7 on 2025-12-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0005_historicocompra_data_horario_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocompra',
            name='data_horario_evento',
            field=models.DateTimeField(),
        ),
    ]
